parser: "@babel/eslint-parser"
env:
  es2021: true
  jquery: true
extends:
  - standard
  - eslint:recommended
  - eslint-config-prettier
globals:
  toastr: true
  Stimulus: true
ignorePatterns:
  - /public
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
