env:
  es2021: true
  jquery: true
extends:
  - standard
  - eslint:recommended
  - eslint-config-prettier
ignorePatterns:
  - /public
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
